<?xml version="1.0" encoding="utf-8"?>
  <Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.8.3</Version>
    <Description>A PVP Series Malmstones Level Calculator</Description>
    <PackageProjectUrl>https://github.com/goatcorp/Malmstone</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
      <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
</Project>
